# Generated by Django 4.2 on 2024-11-05 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("yandex.ru", "Yandex"),
                            ("gmail.com", "Gmail"),
                            ("mail.ru", "Mail.ru"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("sent_date", models.DateTimeField()),
                ("received_date", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(null=True)),
                ("attachments", models.JSONField(max_length=1000)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="emails.emailaccount",
                    ),
                ),
            ],
        ),
    ]
